# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_courses',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='num_tutors',
            field=models.IntegerField(default=0),
        ),
    ]
