# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_tutors',
            field=models.BooleanField(default=False),
        ),
    ]
