# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_department_department_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_school',
        ),
    ]
