# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_department_department_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_school',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
